apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
  labels:
    app: logstash
    app.kubernetes.io/part-of: log-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline

      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.17.0
          ports:
            - name: beats
              containerPort: 5044
              protocol: TCP
            - name: http
              containerPort: 9600    # Logstash monitoring API
              protocol: TCP
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: PIPELINE_WORKERS
              value: "1"
            - name: PIPELINE_BATCH_SIZE
              value: "125"
            # Disable X-Pack monitoring (OpenSearch doesn't support it)
            - name: XPACK_MONITORING_ENABLED
              value: "false"
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/pipeline.conf
              subPath: pipeline.conf
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
